services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arkheia-react-client
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arkheia-node-server
    command: npm start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - database
    env_file: ./server/.env
    networks:
      - app-network

  database:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
    - app-network
    container_name: arkheia-database

networks:
  proxynet:
    name: proxy_network
    external: true

  app-network:
    driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
